---
  - name: Get PHP version
    command: 'php --version'
    register: php_version
    changed_when: false

  - name: Disbale risky functions in PHP 5
    become: true
    ini_file:
      dest={{ php5_ini }}
      section=PHP
      option=disable_functions
      value={{ php_disable_functions }}
      backup=yes
    when: "'PHP 5.' in php_version.stdout"

  - name: Disbale risky functions in PHP 7
    become: true
    ini_file:
      dest={{ php7_ini }}
      section=PHP
      option=disable_functions
      value={{ php_disable_functions }}
      backup=yes
    when: "'PHP 7.' in php_version.stdout"

  - name: Disbale exposures in PHP 5
    become: true
    ini_file:
      dest={{ php5_ini }}
      section=PHP
      option={{ item }}
      value=Off
      backup=yes
    with_items:
      - expose_php
      - display_errors
      - track_errors
      - html_errors
    when: "'PHP 5.' in php_version.stdout"

  - name: Disbale exposures in PHP 7
    become: true
    ini_file:
      dest={{ php7_ini }}
      section=PHP
      option={{ item }}
      value=Off
      backup=yes
    with_items:
      - expose_php
      - display_errors
      - track_errors
      - html_errors
    when: "'PHP 7.' in php_version.stdout"

  - name: Disable apache2 exposures
    become: true
    lineinfile:
      dest=/etc/apache2/conf-enabled/security.conf
      regexp={{ item.regexp }}
      line={{ item.line }}
      state=present
      backup=yes
    with_items:
      - { regexp: "^ServerTokens ", line: "ServerTokens Prod" }
      - { regexp: "^ServerSignature ", line: "ServerSignature Off" }
      - { regexp: "^TraceEnable ", line: "TraceEnable Off" }
    notify: restart apache

  - name: Disable unecessary apache2 mods
    become: true
    apache2_module:
      name={{ item }}
      state=absent
    with_items: "{{ apache_disable_mods }}"
    notify: restart apache

  - name: Disable default apache2 sites
    become: true
    file:
      path={{ apache_sites_enabled_path }}/{{ item }}.conf
      state=absent
    with_items: "{{ apache_disable_sites }}"
    notify: restart apache

  - name: Remove MySQL anonymous users
    become: true
    mysql_user: 
      name="" 
      state=absent 
      login_user={{ mysql_root_user }} 
      login_password={{ mysql_root_pass }}

  - name: Remove MySQL test database
    become: true
    mysql_db: 
      name=test 
      state=absent
      login_user={{ mysql_root_user }}
      login_password={{ mysql_root_pass }}

  - name: Remove MySQL root remote login
    become: true
    command: mysql -u {{ mysql_root_user }} -NBe 'DELETE FROM mysql.user WHERE user = "{{ mysql_root_user }}" AND host NOT IN ("localhost", "127.0.0.1", "::1")'

  - name: List MySQL hosts for the root user
    become: true
    command: mysql -u {{ mysql_root_user }} -NBe 'SELECT host FROM mysql.user WHERE user = "{{ mysql_root_user }}"'
    register: root_mysql_hosts
    changed_when: false
    always_run: true

  - name: Get MySQL minor version
    shell: "mysql --version | awk -F '[ ,.]' '{ print $8 }'"
    register: mysql_minor_version
    changed_when: false

  - name: Get MySQL release version
    shell: "mysql --version | awk -F '[ ,.]' '{ print $9 }'"
    register: mysql_release_version
    changed_when: false

  # Issues identified for the two upcoming tasks:
  # 1. host_all cannot be used becuase of a bug. See bug report at: 
  # 2. mysql_user does NOT always and effectively change the password.
  # 3. simply iterating through hardcoded mysql hosts may NOT work due version differences.
  # Eventually we defer to direct MySQL command.
  # Additional information: http://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html

  - name: Change MySQL (5.7.6 and later) root default password
    become: true
    shell: mysql -u {{ mysql_root_user }} -NBe 'ALTER USER "{{ mysql_root_user }}"@"{{ item }}" IDENTIFIED WITH MYSQL_NATIVE_PASSWORD BY "{{ mysql_root_new_pass }}";'
    with_items: "{{ root_mysql_hosts.stdout_lines }}"
    when: mysql_minor_version.stdout|int >= 7 and mysql_release_version.stdout|int >= 6

  - name: Change MySQL (5.7.5 and earlier) root default password
    become: true
    shell: mysql -u {{ mysql_root_user }} -NBe 'SET PASSWORD FOR "{{ mysql_root_user }}"@"{{ item }}" = PASSWORD("{{ mysql_root_new_pass }}");'
    with_items: "{{ root_mysql_hosts.stdout_lines }}"
    when: mysql_minor_version.stdout|int < 7

  # For removing privileges on test database, see https://github.com/ansible/ansible/issues/5125.
